-- MySQL Script generated by MySQL Workbench
-- Tue Oct 31 10:38:38 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda` DEFAULT CHARACTER SET utf8 ;
USE `tienda` ;

-- -----------------------------------------------------
-- Table `tienda`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`usuario` (
  `id_usuario` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`catalogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`catalogo` (
  `id_catalogo` INT NOT NULL AUTO_INCREMENT,
  `descripcion_catalogo` VARCHAR(45) NOT NULL,
  `id_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_catalogo`),
  INDEX `fk_catalogo_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_catalogo_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tienda`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `descripcion_producto` VARCHAR(100) NOT NULL,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `id_catalogo` INT NOT NULL,
  PRIMARY KEY (`id_producto`, `id_catalogo`),
  CONSTRAINT `fk_producto_catalogo1`
    FOREIGN KEY (`id_catalogo`)
    REFERENCES `tienda`.`catalogo` (`id_catalogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`carrito` (
  `idcarrito` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcarrito`, `id_usuario`),
  INDEX `fk_carrito_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_carrito_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tienda`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `fecha_pedido` DATETIME NULL,
  `estado` VARCHAR(45) NOT NULL,
  `total` INT NOT NULL,
  `id_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pedido_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tienda`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`carrito_has_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`carrito_has_producto` (
  `carrito_idcarrito` INT NOT NULL,
  `producto_id_producto` INT NOT NULL,
  INDEX `fk_carrito_has_producto_carrito1_idx` (`carrito_idcarrito` ASC),
  INDEX `fk_carrito_has_producto_producto1_idx` (`producto_id_producto` ASC),
  CONSTRAINT `fk_carrito_has_producto_carrito1`
    FOREIGN KEY (`carrito_idcarrito`)
    REFERENCES `tienda`.`carrito` (`idcarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_has_producto_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `tienda`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`pedido_has_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`pedido_has_producto` (
  `id_has_pedido` INT NOT NULL AUTO_INCREMENT,
  `pedido_id_pedido` INT NOT NULL,
  `producto_id_producto` INT NOT NULL,
  PRIMARY KEY (`id_has_pedido`),
  INDEX `fk_pedido_has_producto_pedido1_idx` (`pedido_id_pedido` ASC),
  INDEX `fk_pedido_has_producto_producto1_idx` (`producto_id_producto` ASC),
  CONSTRAINT `fk_pedido_has_producto_pedido1`
    FOREIGN KEY (`pedido_id_pedido`)
    REFERENCES `tienda`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_producto_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `tienda`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
